### ISSUE TITLE
Server algorithms

### ISSUE THREAD

**Issue by jayspur11** [pdblasi/NatCom_FinalProject#4]
Movement 'n' birth 'n' death 'n' representations 'n' whatnot
- [x] Decay pheromones
- Divide each value by 2
- [x] Move critters
- Pick Square
  - Square odds = (Herd instinct \* Species pheromones)
    + (Predatory instinct \* MAX[Other pheromones]) **iff** square is valid
    - Instinct values are on scale of -5 to +5
  - Normalize to [0,1] and roulette-select square
- Move critter
  - Update critter's (x,y)
  - Decrement old position on map
  - Increment new position on map
- Update pheromones
  - Pher = (Pher >> 1) | 128
- [x] Handle conflicts
- Decide which is predator
- Decide whether predator spots prey
  - _This decides whether encounter happens_
- Decide whether prey reacts first
  - _This decides which critter selects combat style_
- TRIAL BY ROULETTE
- Update lists..._(the hard part)_

**Comment by jayspur11** [comment]
I've been considering the algorithms for this, and I don't think Python will be quite fast enough, so I'll stick to C++.

**Comment by pdblasi** [comment]
I thought birth and death (minus killing) happened on the client end with the EA?

**Comment by jayspur11** [comment]
Good point! Do we want the client to be responsible for putting agents in the field, or just determining the number of new agents?

**Comment by jayspur11** [comment]
Here's what I'm thinking: the client tells the server how many agents will be added in the next step, and how many will be removed in the next step. The server will proceed to make all the movements, then add the new ones in, then remove the old ones, then handle conflicts. Once that's finished, the server sends out the map and the cycle repeats.

The clients will kick off by giving an initial number of agents (perhaps), then a stream of N birth/death rates for a buffer. Then, a birth/death rate for each map received.

**Comment by pdblasi** [comment]
I just know that I need a population on my side for the EA anyway, my thought was I'd send you updates on the population size, so I think we're thinking along the same lines here.

**Comment by jayspur11** [comment]
Cool!

Should the server include population updates in its responses as well (from conflicts)?

**Comment by pdblasi** [comment]
That's probably the best way.

**Comment by jayspur11** [comment]
Noted it on #2's description!

**Comment by jayspur11** [comment]
Wondering if movement would make more sense as a distributed operation on the clients' side.

**Comment by pdblasi** [comment]
I hadn't planned on storing any location data. What were you thinking?

**Comment by jayspur11** [comment]
There's a lot of calculation needed for movement decisions, so I'm just wondering whether it would be faster to send pheromone info back and forth or to just plow through the calculations. Though just doing the calculations server-side is probably better.

**Comment by pdblasi** [comment]
If we want to do movement on client side, then pheremones should happen client side as well, but the clients don't have access to everyone...

**Comment by jayspur11** [comment]
Right, so the server would have to receive pheromone updates from everyone, then send out what the clients need.

**Comment by jayspur11** [comment]
Who knows, maybe when we write it up server-side it'll just be fast enough.

**Comment by pdblasi** [comment]
I think it'll be fine, it just needs to beat a third of a second. That's ages in computer time.

**Comment by jayspur11** [comment]
Need to update movement algorithm to encourage exploring new areas.
